mod descriptor;
/// Typed attribute expressions for single-attribute operations.
pub mod expression;
/// Typed attribute queries wrapping [`DynamicAttributeQuery`](crate::attribute::query::dynamic::DynamicAttributeQuery).
pub mod query;
/// Type-erased concrete attribute statement.
pub mod statement;
mod the;

pub use descriptor::*;
pub use expression::*;
pub use query::{AttributeQuery, DynamicAttributeQuery, StaticAttributeQuery};
pub use statement::*;
pub use the::*;

pub use crate::artifact::{ArtifactsAttribute, Cause, DialogArtifactsError, Entity, Value};
pub use crate::schema::Cardinality;
pub use crate::types::{Scalar, Type, Typed};
pub use crate::{Predicate, Premise, Term};

/// A typed attribute definition generated by `#[derive(Attribute)]`.
///
/// Each attribute newtype (e.g. `struct Name(String)`) implements this
/// trait, which provides:
/// - The scalar Rust type of the attribute's values (`Type`).
/// - Access to the inner value via [`value()`](Attribute::value).
///
/// Attributes are the atomic building blocks of concepts: a concept is
/// a set of attributes that together describe an entity type.
///
/// For schema metadata, see [`Descriptor<AttributeDescriptor>`](crate::Descriptor).
/// For the fluent `::of()` expression builder, see [`StaticAttributeExpressionBuilder`].
pub trait Attribute: Predicate + Sized {
    /// The Rust scalar type of this attribute's values.
    type Type: Scalar;

    /// Returns a reference to the inner value.
    fn value(&self) -> &Self::Type;
}

#[cfg(test)]
mod tests {
    use crate::artifact::Type;
    use crate::attribute::{Attribute, AttributeDescriptor, Cardinality};
    use crate::term::Term;
    use crate::the;

    mod person {
        use std::sync::OnceLock;

        use crate::artifact::Value;
        use crate::attribute::expression::typed::StaticAttributeStatement;
        use crate::attribute::query::StaticAttributeQuery;
        use crate::attribute::{Attribute, AttributeDescriptor, StaticAttributeExpressionBuilder};
        use crate::descriptor::Descriptor;
        use crate::term::Term;
        use crate::the;
        use crate::types::{TypeDescriptor, Typed};
        use crate::{Cardinality, Predicate};

        #[derive(Clone, Debug)]
        pub struct Name(pub String);

        impl Predicate for Name {
            type Conclusion = StaticAttributeStatement<Self>;
            type Application = StaticAttributeQuery<Self>;
            type Descriptor = AttributeDescriptor;
        }

        impl Attribute for Name {
            type Type = String;

            fn value(&self) -> &Self::Type {
                &self.0
            }
        }

        impl Descriptor<AttributeDescriptor> for Name {
            fn descriptor() -> &'static AttributeDescriptor {
                static DESCRIPTOR: OnceLock<AttributeDescriptor> = OnceLock::new();
                DESCRIPTOR.get_or_init(|| {
                    AttributeDescriptor::new(
                        the!("person/name"),
                        "The name of the person",
                        Cardinality::One,
                        <<String as Typed>::Descriptor as TypeDescriptor>::TYPE,
                    )
                })
            }
        }

        impl StaticAttributeExpressionBuilder for Name {}

        impl From<String> for Name {
            fn from(value: String) -> Self {
                Self(value)
            }
        }

        impl From<Name> for Term<String> {
            fn from(attr: Name) -> Self {
                Term::Constant(<String as Into<Value>>::into(attr.0))
            }
        }
    }

    #[dialog_common::test]
    fn it_derives_person_name() {
        use crate::descriptor::Descriptor;
        let _name = person::Name("hello".into());
        assert_eq!(person::Name::descriptor().domain(), "person");
        assert_eq!(person::Name::descriptor().name(), "name");
    }

    mod employee_derive {
        use crate::Attribute;

        /// Name of the employee
        #[derive(Attribute, Clone)]
        pub struct Name(pub String);

        /// Job title of the employee
        #[derive(Attribute, Clone)]
        pub struct Job(pub String);

        /// Salary of the employee
        #[derive(Attribute, Clone)]
        pub struct Salary(pub u32);
    }

    mod person_derive {
        use crate::Attribute;

        /// Name of the person
        #[derive(Attribute, Clone)]
        pub struct Name(pub String);

        /// Employees managed by this person
        #[derive(Attribute, Clone)]
        #[cardinality(many)]
        pub struct Manages(pub crate::Entity);
    }

    #[dialog_common::test]
    fn it_derives_employee_name() {
        let name = employee_derive::Name("Alice".to_string());

        assert_eq!(
            employee_derive::Name::descriptor().domain(),
            "employee-derive"
        );
        assert_eq!(employee_derive::Name::descriptor().name(), "name");
        assert_eq!(
            employee_derive::Name::descriptor().description(),
            "Name of the employee"
        );
        assert_eq!(employee_derive::Name::cardinality(), Cardinality::One);
        assert_eq!(name.value(), "Alice");
        assert_eq!(
            employee_derive::Name::descriptor().the().to_string(),
            "employee-derive/name"
        );
    }

    #[dialog_common::test]
    fn it_derives_employee_job() {
        let job = employee_derive::Job("Engineer".to_string());

        assert_eq!(
            employee_derive::Job::descriptor().domain(),
            "employee-derive"
        );
        assert_eq!(employee_derive::Job::descriptor().name(), "job");
        assert_eq!(
            employee_derive::Job::descriptor().description(),
            "Job title of the employee"
        );
        assert_eq!(employee_derive::Job::cardinality(), Cardinality::One);
        assert_eq!(job.value(), "Engineer");
        assert_eq!(
            employee_derive::Job::descriptor().the().to_string(),
            "employee-derive/job"
        );
    }

    #[dialog_common::test]
    fn it_derives_employee_salary() {
        let salary = employee_derive::Salary(100000);

        assert_eq!(
            employee_derive::Salary::descriptor().domain(),
            "employee-derive"
        );
        assert_eq!(employee_derive::Salary::descriptor().name(), "salary");
        assert_eq!(
            employee_derive::Salary::descriptor().description(),
            "Salary of the employee"
        );
        assert_eq!(employee_derive::Salary::cardinality(), Cardinality::One);
        assert_eq!(salary.value(), &100000u32);
        assert_eq!(
            employee_derive::Salary::descriptor().the().to_string(),
            "employee-derive/salary"
        );
    }

    #[dialog_common::test]
    fn it_derives_person_domain() {
        let name = person_derive::Name("Bob".to_string());

        assert_eq!(person_derive::Name::descriptor().domain(), "person-derive");
        assert_eq!(person_derive::Name::descriptor().name(), "name");
        assert_eq!(
            person_derive::Name::descriptor().the().to_string(),
            "person-derive/name"
        );
        assert_eq!(name.value(), "Bob");
    }

    #[dialog_common::test]
    fn it_derives_cardinality_many() {
        assert_eq!(person_derive::Manages::cardinality(), Cardinality::Many);
        assert_eq!(
            person_derive::Manages::descriptor().description(),
            "Employees managed by this person"
        );
        assert_eq!(
            person_derive::Manages::descriptor().domain(),
            "person-derive"
        );
    }

    mod record_derive {
        use crate::Attribute;
        use crate::artifact::{RecordError, RecordFormat, Recorded};

        /// A toy record format: a list of lines, encoded newline-joined.
        #[derive(Clone, Debug, PartialEq)]
        pub struct Journal(pub Vec<String>);

        impl RecordFormat for Journal {
            fn decode(bytes: &[u8]) -> Result<Self, RecordError> {
                let text = str::from_utf8(bytes)
                    .map_err(|error| RecordError::Decode(error.to_string()))?;
                Ok(Journal(match text {
                    "" => Vec::new(),
                    text => text.split('\n').map(String::from).collect(),
                }))
            }

            fn encode(&self) -> Result<Vec<u8>, RecordError> {
                Ok(self.0.join("\n").into_bytes())
            }
        }

        /// Collaboratively edited body
        #[derive(Attribute, Clone)]
        pub struct Body(pub Recorded<Journal>);
    }

    #[dialog_common::test]
    fn it_derives_record_attribute() {
        use crate::artifact::Recorded;

        let descriptor = record_derive::Body::descriptor();
        assert_eq!(descriptor.domain(), "record-derive");
        assert_eq!(descriptor.name(), "body");
        assert_eq!(descriptor.description(), "Collaboratively edited body");
        assert_eq!(descriptor.cardinality(), Cardinality::One);
        assert_eq!(descriptor.content_type(), Some(Type::Record));

        let journal = record_derive::Journal(vec!["hello".into(), "world".into()]);
        let body = record_derive::Body(Recorded::new(journal.clone()).unwrap());
        assert_eq!(*body.value().realize().unwrap(), journal);
    }

    #[dialog_common::test]
    fn it_converts_record_attribute_into_term() {
        use crate::artifact::{Recorded, Value};

        let recorded = Recorded::new(record_derive::Journal(vec!["entry".into()])).unwrap();
        let body = record_derive::Body(recorded.clone());

        let term: Term<Recorded<record_derive::Journal>> = body.into();
        assert!(term.is_constant());
        assert_eq!(term, Term::Constant(Value::from(recorded)));
    }

    mod custom_ns_derive {
        use crate::Attribute;

        /// Custom domain override test
        #[derive(Attribute, Clone)]
        #[domain = "custom"]
        pub struct Field(pub String);
    }

    #[dialog_common::test]
    fn it_overrides_domain_via_derive() {
        let field = custom_ns_derive::Field("value".to_string());

        assert_eq!(custom_ns_derive::Field::descriptor().domain(), "custom");
        assert_eq!(custom_ns_derive::Field::descriptor().name(), "field");
        assert_eq!(
            custom_ns_derive::Field::descriptor().the().to_string(),
            "custom/field"
        );
        assert_eq!(field.value(), "value");
    }

    mod account_name {
        use crate::Attribute;

        /// Account holder's name
        #[derive(Attribute, Clone)]
        pub struct Name(pub String);
    }

    mod ns_my {
        pub mod config {
            use crate::Attribute;

            /// Configuration key
            #[derive(Attribute, Clone)]
            pub struct Key(pub String);
        }
    }

    #[derive(crate::Attribute, Clone)]
    #[domain("my.custom.namespace")]
    pub struct NsValue(pub String);

    #[derive(crate::Attribute, Clone)]
    #[domain(custom)]
    pub struct NsCustomValue(pub String);

    #[derive(crate::Attribute, Clone)]
    #[domain("io.gozala")]
    pub struct NsDottedValue(pub String);

    mod ns_my_app {
        pub mod user_profile {
            use crate::Attribute;

            /// User email address
            #[derive(Attribute, Clone)]
            pub struct Email(pub String);
        }
    }

    #[dialog_common::test]
    fn it_converts_underscores_to_hyphens() {
        assert_eq!(account_name::Name::descriptor().domain(), "account-name");
        assert_eq!(account_name::Name::descriptor().name(), "name");
        assert_eq!(
            account_name::Name::descriptor().the().to_string(),
            "account-name/name"
        );
    }

    #[dialog_common::test]
    fn it_derives_nested_module_domain() {
        assert_eq!(ns_my::config::Key::descriptor().domain(), "config");
        assert_eq!(ns_my::config::Key::descriptor().name(), "key");
        assert_eq!(
            ns_my::config::Key::descriptor().the().to_string(),
            "config/key"
        );
    }

    #[dialog_common::test]
    fn it_overrides_domain_explicitly() {
        assert_eq!(NsValue::descriptor().domain(), "my.custom.namespace");
        assert_eq!(NsValue::descriptor().name(), "ns-value");
        assert_eq!(
            NsValue::descriptor().the().to_string(),
            "my.custom.namespace/ns-value"
        );
    }

    #[dialog_common::test]
    fn it_accepts_domain_identifier_syntax() {
        assert_eq!(NsCustomValue::descriptor().domain(), "custom");
        assert_eq!(NsCustomValue::descriptor().name(), "ns-custom-value");
        assert_eq!(
            NsCustomValue::descriptor().the().to_string(),
            "custom/ns-custom-value"
        );
    }

    #[dialog_common::test]
    fn it_accepts_domain_string_literal() {
        assert_eq!(NsDottedValue::descriptor().domain(), "io.gozala");
        assert_eq!(NsDottedValue::descriptor().name(), "ns-dotted-value");
        assert_eq!(
            NsDottedValue::descriptor().the().to_string(),
            "io.gozala/ns-dotted-value"
        );
    }

    #[dialog_common::test]
    fn it_converts_nested_underscores() {
        assert_eq!(
            ns_my_app::user_profile::Email::descriptor().domain(),
            "user-profile"
        );
        assert_eq!(ns_my_app::user_profile::Email::descriptor().name(), "email");
        assert_eq!(
            ns_my_app::user_profile::Email::descriptor()
                .the()
                .to_string(),
            "user-profile/email"
        );
    }

    #[dialog_common::test]
    fn it_preserves_all_metadata() {
        let name = account_name::Name("John Doe".to_string());

        assert_eq!(account_name::Name::descriptor().domain(), "account-name");
        assert_eq!(account_name::Name::descriptor().name(), "name");
        assert_eq!(
            account_name::Name::descriptor().description(),
            "Account holder's name"
        );
        assert_eq!(account_name::Name::cardinality(), Cardinality::One);
        assert_eq!(name.value(), "John Doe");
    }

    mod test_pascal {
        use crate::Attribute;

        #[derive(Attribute, Clone)]
        pub struct UserName(pub String);

        #[derive(Attribute, Clone)]
        pub struct HTTPRequest(pub String);

        #[derive(Attribute, Clone)]
        pub struct APIKey(pub String);
    }

    #[dialog_common::test]
    fn it_converts_pascal_to_kebab() {
        assert_eq!(test_pascal::UserName::descriptor().name(), "user-name");
    }

    #[dialog_common::test]
    fn it_converts_consecutive_capitals() {
        assert_eq!(
            test_pascal::HTTPRequest::descriptor().name(),
            "http-request"
        );
        assert_eq!(test_pascal::APIKey::descriptor().name(), "api-key");
    }

    #[dialog_common::test]
    fn it_exposes_static_values() {
        let descriptor = test_pascal::UserName::descriptor();

        assert!(!descriptor.domain().is_empty());
        assert_eq!(descriptor.name(), "user-name");
        let _ = descriptor.description();
    }

    #[dialog_common::test]
    fn it_exposes_static_schema() {
        let schema = &test_pascal::UserName::descriptor();
        assert_eq!(schema.name(), "user-name");
        assert_eq!(schema.cardinality(), Cardinality::One);
    }

    mod employee_ident {
        use crate::Attribute;

        #[derive(Attribute, Clone)]
        pub struct Name(pub String);

        #[derive(Attribute, Clone)]
        pub struct Salary(pub u32);

        #[derive(Attribute, Clone)]
        pub struct Job(pub String);
    }

    mod person_ident {
        use crate::Attribute;

        #[derive(Attribute, Clone)]
        pub struct Name(pub String);
    }

    #[dialog_common::test]
    fn it_produces_stable_hash() {
        let hash1 = employee_ident::Name::descriptor().hash();
        let hash2 = employee_ident::Name::descriptor().hash();

        assert_eq!(
            hash1, hash2,
            "Same attribute should produce identical hashes"
        );
    }

    #[dialog_common::test]
    fn it_hashes_differently_for_different_attributes() {
        let name_hash = employee_ident::Name::descriptor().hash();
        let salary_hash = employee_ident::Salary::descriptor().hash();
        let job_hash = employee_ident::Job::descriptor().hash();

        assert_ne!(
            name_hash, salary_hash,
            "Name and Salary should have different hashes"
        );
        assert_ne!(
            name_hash, job_hash,
            "Name and Job should have different hashes"
        );
        assert_ne!(
            salary_hash, job_hash,
            "Salary and Job should have different hashes"
        );
    }

    #[dialog_common::test]
    fn it_hashes_differently_for_different_domains() {
        let employee_name_hash = employee_ident::Name::descriptor().hash();
        let person_name_hash = person_ident::Name::descriptor().hash();

        assert_ne!(
            employee_name_hash, person_name_hash,
            "employee::Name and person::Name should have different hashes"
        );
    }

    #[dialog_common::test]
    fn it_formats_uri() {
        let uri = employee_ident::Name::descriptor().to_uri();

        assert!(
            uri.starts_with("the:"),
            "URI should start with 'the:' prefix"
        );
        assert!(uri.len() > 4, "URI should have content after 'the:' prefix");
    }

    #[dialog_common::test]
    fn it_round_trips_uri() {
        let uri = employee_ident::Name::descriptor().to_uri();
        let parsed_hash = AttributeDescriptor::parse_uri(&uri);

        assert!(parsed_hash.is_some(), "Should be able to parse valid URI");
        assert_eq!(
            parsed_hash.unwrap(),
            employee_ident::Name::descriptor().hash(),
            "Parsed hash should match original hash"
        );
    }

    #[dialog_common::test]
    fn it_rejects_invalid_uri() {
        assert!(
            AttributeDescriptor::parse_uri("invalid").is_none(),
            "Should fail to parse URI without 'the:' prefix"
        );

        assert!(
            AttributeDescriptor::parse_uri("the:invalid").is_none(),
            "Should fail to parse URI with invalid hash"
        );

        assert!(
            AttributeDescriptor::parse_uri("concept:abcd").is_none(),
            "Should fail to parse URI with wrong prefix"
        );
    }

    #[dialog_common::test]
    fn it_produces_stable_schema_hash() {
        let schema_hash = employee_ident::Name::descriptor().hash();
        let trait_hash = employee_ident::Name::descriptor().hash();

        assert_eq!(
            schema_hash, trait_hash,
            "Schema hash and trait hash should match"
        );
    }

    #[dialog_common::test]
    fn it_encodes_to_cbor() {
        let cbor1 = employee_ident::Name::descriptor().to_cbor_bytes();
        let cbor2 = employee_ident::Name::descriptor().to_cbor_bytes();

        assert_eq!(cbor1, cbor2, "CBOR encoding should be deterministic");
        assert!(!cbor1.is_empty(), "CBOR encoding should not be empty");
    }

    #[dialog_common::test]
    fn it_excludes_description_from_hash() {
        let attr1 = AttributeDescriptor::new(
            the!("user/email"),
            "Primary email address",
            Cardinality::One,
            Some(Type::String),
        );

        let attr2 = AttributeDescriptor::new(
            the!("user/email"),
            "User's email for notifications",
            Cardinality::One,
            Some(Type::String),
        );

        assert_eq!(
            attr1.hash(),
            attr2.hash(),
            "Attributes with different descriptions should have the same hash"
        );

        assert_eq!(
            attr1.to_uri(),
            attr2.to_uri(),
            "Attributes with different descriptions should have the same URI"
        );
    }

    mod employee_term {
        use crate::Attribute;

        #[derive(Attribute, Clone)]
        pub struct Name(pub String);

        #[derive(Attribute, Clone)]
        pub struct Job(pub String);

        #[derive(Attribute, Clone)]
        pub struct Salary(pub u32);
    }

    #[dialog_common::test]
    fn it_converts_into_term() {
        let name = employee_term::Name("Alice".into());
        let name_term: Term<String> = name.into();
        assert!(name_term.is_constant());

        let job = employee_term::Job("Engineer".into());
        let job_term: Term<String> = job.into();
        assert!(job_term.is_constant());

        let salary = employee_term::Salary(65000);
        let salary_term: Term<u32> = salary.into();
        assert!(salary_term.is_constant());
    }

    #[dialog_common::test]
    fn it_creates_from_method() {
        let name = employee_term::Name::from("Alice");
        assert_eq!(name.value(), "Alice");

        let job = employee_term::Job::from("Engineer");
        assert_eq!(job.value(), "Engineer");

        let salary = employee_term::Salary::from(65000u32);
        assert_eq!(*salary.value(), 65000);

        let name_term: Term<String> = employee_term::Name::from("Bob").into();
        assert!(name_term.is_constant());
    }

    #[dialog_common::test]
    fn it_uses_into_in_match_construction() {
        use crate::{Concept, Entity, Query, Term};

        #[derive(Concept, Debug, Clone)]
        pub struct Employee {
            pub this: Entity,
            pub name: employee_term::Name,
            pub job: employee_term::Job,
            pub salary: employee_term::Salary,
        }

        let pattern = Query::<Employee> {
            this: Term::var("e"),
            name: Term::var("name"),
            salary: Term::var("salary"),
            job: employee_term::Job("Engineer".into()).into(),
        };

        assert!(pattern.job.is_constant());

        let pattern2 = Query::<Employee> {
            this: Term::var("e"),
            name: Term::var("name"),
            salary: Term::var("salary"),
            job: employee_term::Job::from("Engineer").into(),
        };

        assert!(pattern2.job.is_constant());
    }
}
